/**
 * One student's run, end to end, as a document.
 *
 * The claim this product rests on is a chain: a **concept** becomes a **decision
 * opportunity**, a student makes a **decision** and gives their **reasoning**, the world
 * produces a **consequence**, the student **adapts**, later **explains**, and a teacher reads
 * **evidence they can check**. Every link of that is asserted somewhere in this suite. Nothing
 * printed the whole chain for one child, which is the thing a person actually has to see
 * before believing it.
 *
 * So this drives the shipped reducer through a whole run, hands the log to the shipped
 * observers, and writes down what came back. It invents nothing and formats nothing that is
 * not a value the product produced — where a level is absent it prints the absence.
 *
 * It lives beside `runChallenge` rather than in `scripts/`, and the reason is that
 * `scripts/` is outside the lint path and outside `tsconfig`: a receipt generator nobody
 * typechecks produces a stale receipt nobody notices. `chainReceipt.test.ts` diffs its output
 * against the committed document, so the receipt in `gauntlet/evidence/` cannot quietly stop
 * being true of the product.
 */
import { COMPETENCIES, requiredEvidenceRequirementsFor } from "../domain/competency/competencies";
import { observeCompetencies } from "../domain/competency/observe";
import { evidenceTrail } from "../domain/competency/trail";
import { RUBRIC_VERSION } from "../domain/competency/types";
import { observeBasketballFromLog } from "../domain/scenario/worlds/basketball/observer";
import { runChallenge } from "./runChallenge";

export function chainDocument(): string {
  const RUN = {
    setupId: "cousin-room",
    reserveSeat: true,
    takeClinics: true,
    countCompletion: true,
    countOutcome: true,
    countCompletionFinal: true,
    split: { goal: 0.5, reserve: 0.3 },
    closeOpeningInto: "reserve",
    defenseText:
      "The reserve took the hit, not the course seat. I already had the sports-media completion "
      + "counted, so the plan holds even if the outcome bonus does not land.",
  } as const;

  const state = runChallenge(RUN);
  const log = state.log;
  const observations = observeBasketballFromLog(log);
  const results = observeCompetencies(observations);
  const trail = evidenceTrail(log, observations);

  const kinds = [...new Set(log.map((event) => event.type))];
  const judgements = trail.moments.flatMap((moment) => moment.judgements);
  const out: string[] = [];
  const w = (line = "") => out.push(line);

  w("# One student, end to end");
  w();
  w("Generated by `scripts/evidence-chain.ts`, which drives the shipped reducer through a whole");
  w("run and hands the log to the shipped observers. Every value below is one the product");
  w("produced. Regenerate with:");
  w();
  w("```bash");
  w("npx tsx scripts/evidence-chain.ts > gauntlet/evidence/chain-one-student.md");
  w("```");
  w();
  w("**The run.** The cousin's room, the course seat reserved early, the clinics taken, both");
  w("conditional payments counted, the opening plan closed by naming the backup-money row as the");
  w("one that takes the rest, and a written defence at the end.");
  w();
  w("## The chain");
  w();
  w("| Link | What the product holds for this student |");
  w("| --- | --- |");
  w(`| **CONCEPT** | ${COMPETENCIES.length} BOW competencies, each with evidence requirements read under one 5/4/3/2/0 rubric — no level 1. Rubric version \`${RUBRIC_VERSION}\`. This run touched ${results.length}. |`);
  w(`| **DECISION OPPORTUNITY** | ${log.length} events, ${kinds.length} distinct kinds, all from the closed vocabulary in \`evidence/types.ts\`. |`);
  w(`| **STUDENT DECISION** | ${kinds.filter((kind) => /SELECTED|TOGGLED|ASSIGNED|SETTLED|DECIDED|RANKED/.test(kind)).map((kind) => `\`${kind}\``).join(", ")}. |`);
  w("| **STUDENT REASONING** | `COMPETING_CLAIMS_SETTLED` carries the reason the student chose; `DEFENSE_SUBMITTED` carries their own paragraph. |");
  w("| **CONSEQUENCE** | The season resolves against the plan the student saved, and Week 8 prints what each decision did, with its counterfactual. |");
  w("| **ADAPTATION** | Week 5 breaks the plan; the repair is a second full board, observed separately as `adapt-a-plan`. |");
  w("| **LATER EXPLANATION** | The written defence. Gated for substance, and scored by a person — never by the product. |");
  w(`| **TEACHER-READABLE EVIDENCE** | ${trail.moments.length} anchored moments carrying ${judgements.length} judgements, each with the event that settled it and the observer's own sentence. |`);
  w();
  w("## The judgements, as a teacher reads them");
  w();
  w("Each is anchored to the moment it was **settled** — the last event the observer cited, not");
  w("the first — because hanging a conclusion on the first of its evidence puts it before its");
  w("own reasons.");
  w();

  for (const moment of trail.moments) {
    for (const judgement of moment.judgements) {
      const level = judgement.level === null ? "not observed" : String(judgement.level);
      const capped = judgement.cappedBySupport ? " · **capped by the support given, not by the student**" : "";
      const superseded = judgement.superseded ? " · *superseded by a later reading*" : "";
      w(`### ${judgement.label}`);
      w();
      w(`\`${judgement.evidenceRequirementId}\` · level **${level}** · support \`${judgement.supportLevel}\`${capped}${superseded}`);
      w();
      w(`> ${judgement.reason}`);
      w();
      w(`Settled at \`${moment.eventId}\` — \`${moment.type}\`, sequence ${moment.sequence}, stage \`${moment.stage}\`.`);
      w(`Cited: ${judgement.evidenceRefs.map((ref) => `\`${ref}\``).join(", ") || "—"}.`);
      w();
      w(`*The rule it was read against:* ${judgement.observableRule}`);
      if (judgement.misconception) w(`*The misconception it is looking for:* ${judgement.misconception}`);
      w();
    }
  }

  w("## What the competencies came to");
  w();
  w("The state is computed from the **required** requirements alone. An optional one is real");
  w("evidence and is still reported — it is not the bar. That is why two competencies below can");
  w("both have an unobserved last row and land in different states, and the `required` column is");
  w("printed so the difference is checkable rather than surprising.");
  w();
  for (const result of results) {
    const required = new Set(requiredEvidenceRequirementsFor(result.competencyId).map((row) => row.id));
    w(`### \`${result.competencyId}\` — **${result.state}**`);
    w();
    w("| Requirement | Level | Required |");
    w("| --- | --- | --- |");
    for (const level of result.levels) {
      const shown = level.level === null ? "**not observed**" : String(level.level);
      w(`| \`${level.evidenceRequirementId}\` | ${shown} | ${required.has(level.evidenceRequirementId) ? "yes" : "no"} |`);
    }
    w();
  }

  w("## What is deliberately absent");
  w();
  w(`\`notObserved\`: ${trail.notObserved.length} ${trail.notObserved.length === 1 ? "entry" : "entries"}.`);
  for (const judgement of trail.notObserved) {
    w(`- \`${judgement.evidenceRequirementId}\` — ${judgement.reason}`);
  }
  w();
  w("*Incomplete* above is not a low score and is not a failure. Where the run cannot say, the");
  w("product says nothing: an unread written explanation is a fact about a teacher's marking");
  w("backlog, and reporting it as a zero would make it a fact about a child.");
  w();
  w("### The rows that wait on a person, by design");
  w();
  w("Every requirement whose `kind` is `explanation` is scored by a teacher and never by the");
  w("product. That is why two of the three competencies above are still open on a run where the");
  w("student did everything: the machine has finished and the marking has not.");
  w();
  for (const result of results) {
    const rows = COMPETENCIES.find((competency) => competency.id === result.competencyId)?.evidenceRequirements ?? [];
    const written = rows.filter((row) => row.kind === "explanation");
    if (written.length === 0) continue;
    for (const row of written) {
      const observed = result.levels.find((level) => level.evidenceRequirementId === row.id);
      w(`- \`${row.id}\` — *${row.label}* · ${row.required ? "required" : "optional"} · currently ${observed?.level === null || observed === undefined ? "**unmarked**" : String(observed.level)}`);
    }
  }
  w();
  w("So a run can be complete and a competency still open. The product does not close that gap by");
  w("guessing, and there is no path in it by which a machine scores a child's writing.");

  return `${out.join("\n")}\n`;

}
