import { chromium } from "playwright";
import fs from "node:fs";
const BASE="http://127.0.0.1:5603", CODE=process.env.CODE, OUT=process.env.OUT;
fs.mkdirSync(OUT,{recursive:true});
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await (await b.newContext({viewport:{width:1366,height:1200}})).newPage();
p.on("pageerror",(e)=>console.log("PAGEERROR:",e.message));
let step=0;
const dump=async(tag)=>{step+=1;const n=String(step).padStart(2,"0");
  const t=await p.evaluate(()=>document.body.innerText);
  fs.writeFileSync(`${OUT}/${n}-${tag}.txt`,t);
  await p.screenshot({path:`${OUT}/${n}-${tag}.png`,fullPage:true});
  console.log(`\n##### ${n} ${tag} #####\n${t}`);};
const ctrls=async()=>{const o=[];
  for(const e of await p.locator("button:visible").all()) o.push("BTN «"+(((await e.innerText())||(await e.getAttribute("aria-label"))||"").replace(/\s+/g," ").trim())+"»"+((await e.getAttribute("aria-disabled"))==="true"?"[DIS]":""));
  for(const e of await p.locator("input:visible").all()) o.push("INP «"+((await e.getAttribute("aria-label"))||(await e.getAttribute("id"))||"?")+"»");
  console.log("CTRLS:",JSON.stringify(o));};
const B=async(name,{exact=false,nth=0}={})=>{await p.getByRole("button",{name,exact}).nth(nth).click();await p.waitForTimeout(650);};
const sum=async(label,val)=>{const i=p.getByLabel(label).first();await i.fill(String(val));await p.getByRole("button",{name:/^Check$/}).first().click();await p.waitForTimeout(800);};
const bump=async(label,times,dir="Increase")=>{for(let i=0;i<times;i++){await p.getByRole("button",{name:new RegExp(`${dir} ${label} by`)}).first().click();await p.waitForTimeout(90);}};
try{
  await p.goto(`${BASE}/join`,{waitUntil:"networkidle"});
  await p.getByLabel(/class code/i).fill(CODE);
  await p.getByRole("button",{name:"Next"}).click();
  await p.locator("#display-name").waitFor({timeout:20000});
  await p.locator("#display-name").fill("EconCritic");
  await p.getByRole("button",{name:/Go in/i}).click();
  await p.waitForTimeout(1500);
  await p.getByRole("link",{name:/^Start/}).first().click();
  await p.waitForTimeout(1200);
  await p.getByRole("button",{name:/Start this one/}).nth(1).click();
  await p.waitForTimeout(1200);
  await B(/Take this booth: Middle Row/);
  await sum("What you owe before you open", 390);
  await B(/See what is left/);
  await dump("money-screen");
  await B(/Yes — count it in: Sunrise Yoga/);
  await B(/No — leave it out: Sell-out rebate/);
  await dump("money-answered"); await ctrls();
  await sum("What is left to plan with", 1510);
  await dump("cash-to-plan"); await ctrls();
  await B(/Split the money/);
  await dump("plan-board"); await ctrls();
}catch(e){console.log("ERR",e.message); await dump("error");}
await b.close();
