import { chromium } from "playwright";
const BASE="http://127.0.0.1:5603", CODE=process.env.CODE;
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await (await b.newContext({viewport:{width:1366,height:1200}})).newPage();
const B=async(n,{nth=0}={})=>{await p.getByRole("button",{name:n}).nth(nth).click();await p.waitForTimeout(450);};
const sum=async(l,v)=>{await p.getByLabel(l).first().fill(String(v));await p.getByRole("button",{name:/^Check$/}).first().click();await p.waitForTimeout(650);};
const val=async(line)=>{const t=await p.evaluate(()=>document.body.innerText);const m=t.match(new RegExp(line+"\\n[^\\n]*\\n(\\$[\\d,]+)"));return m?m[1]:"?";};
const totals=async()=>{const t=await p.evaluate(()=>document.body.innerText);
  return (t.match(/TO PLAN WITH\n(\$[\d,-]+)\nON THE THREE LINES\n(\$[\d,-]+)\nSTILL TO PLACE\n(-?\$[\d,]+)/)||[]).slice(1).join(" | ");};
await p.goto(`${BASE}/join`,{waitUntil:"networkidle"});
await p.getByLabel(/class code/i).fill(CODE);
await p.getByRole("button",{name:"Next"}).click();
await p.locator("#display-name").waitFor({timeout:20000});
await p.locator("#display-name").fill("IncProbe2");
await p.getByRole("button",{name:/Go in/i}).click(); await p.waitForTimeout(1400);
await p.getByRole("link",{name:/^Start/}).first().click(); await p.waitForTimeout(1100);
await p.getByRole("button",{name:/Start this one/}).nth(1).click(); await p.waitForTimeout(1100);
await B(/Take this booth: Middle Row/);
await sum("What you owe before you open", 390);
await B(/See what is left/);
await B(/No — leave it out: Sunrise Yoga/);
await B(/No — leave it out: Sell-out rebate/);
await sum("What is left to plan with", 1510);
await B(/Split the money/);
for (let i=0;i<31;i++){ await p.getByRole("button",{name:/Increase Stock by/}).first().click(); await p.waitForTimeout(40); }
console.log("after 31 × +50 on Stock: stock=",await val("Stock"), "| totals:", await totals());
await p.getByRole("button",{name:/Decrease Stock by/}).first().click(); await p.waitForTimeout(300);
console.log("after one − on Stock  : stock=",await val("Stock"), "| totals:", await totals());
await p.getByRole("button",{name:/Increase Cushion by/}).first().click(); await p.waitForTimeout(300);
console.log("after one + on Cushion:", "cushion=",await val("Cushion"), "| totals:", await totals());
await p.screenshot({path:process.env.OUT+"/increment-snapback.png",fullPage:true});
await b.close();
