/**
 * What BOW can actually assess, one row per state topic, computed from the product.
 *
 * The objectives page already tells a teacher the truth one objective at a time, and it
 * derives the number rather than storing it. Nothing answers the question a district asks
 * first, which is not about an objective: *can I use this for my credit unit?* That question
 * is asked one topic at a time and the product had no sentence for it, so this writes one —
 * from `availability.ts` and the mapping table, never from a hand-kept list.
 *
 * **A topic is covered when at least one of its objectives is demonstrable**, and an
 * objective is demonstrable only when a competency mapped `full` to it is available, or when
 * every competency in its completion rule is. `partial` mappings never make a topic covered:
 * that is the whole point of the three coverage words, and a topic summary that counted them
 * would be the over-claim this file exists to publish.
 *
 *     npx tsx scripts/module-coverage.ts     # writes MODULE_COVERAGE.md
 *
 * `moduleCoverage.test.ts` regenerates it and fails if the committed file disagrees, so the
 * document cannot drift from the code the way a hand-written coverage table always does.
 */
import { NYSED_2026_STANDARDS, NYSED_2026_TOPICS } from "../src/domain/standards/frameworks/nysed-2026";
import { NYSED_2026_COMPLETION_RULES, NYSED_2026_MAPPINGS } from "../src/domain/standards/mappings/nysed-2026";
import { COMPETENCIES, requiredEvidenceRequirementsFor } from "../src/domain/competency/competencies";
import { availableCompetencyIds, worldsAssessing } from "../src/domain/competency/availability";
import type { CompetencyId } from "../src/domain/competency/types";

export type ObjectiveVerdict = "demonstrable" | "evidence-only" | "not-assessable";

export interface ObjectiveRow {
  code: string;
  shortLabel: string;
  verdict: ObjectiveVerdict;
  /** The competencies mapped `full` to it, and whether each is built. */
  fullMappings: { competencyId: CompetencyId; available: boolean }[];
  /** Present when a completion rule bundles several skills under one number. */
  requires?: { competencyId: CompetencyId; available: boolean }[];
}

export interface TopicRow {
  code: string;
  name: string;
  objectives: ObjectiveRow[];
  demonstrable: number;
}

export function readCoverage(): TopicRow[] {
  const available = availableCompetencyIds();
  return NYSED_2026_TOPICS.map((topic) => {
    const objectives = NYSED_2026_STANDARDS.filter((standard) => standard.topicCode === topic.code).map(
      (standard): ObjectiveRow => {
        const rows = NYSED_2026_MAPPINGS.filter((mapping) => mapping.standardCode === standard.code);
        const fullMappings = rows
          .filter((mapping) => mapping.coverage === "full")
          .map((mapping) => ({ competencyId: mapping.competencyId, available: available.has(mapping.competencyId) }));
        const rule = NYSED_2026_COMPLETION_RULES.find((entry) => entry.standardCode === standard.code);
        const requires = rule?.requires.map((competencyId) => ({ competencyId, available: available.has(competencyId) }));
        // A completion rule wins outright where there is one: an objective that bundles three
        // skills is not demonstrated by whichever of the three happens to be built.
        const demonstrable = requires
          ? requires.every((entry) => entry.available)
          : fullMappings.some((entry) => entry.available);
        const anyEvidence = rows.some((mapping) => mapping.coverage !== "supporting" && available.has(mapping.competencyId));
        return {
          code: standard.code,
          shortLabel: standard.shortLabel,
          verdict: demonstrable ? "demonstrable" : anyEvidence ? "evidence-only" : "not-assessable",
          fullMappings,
          ...(requires ? { requires } : {}),
        };
      },
    );
    return {
      code: topic.code,
      name: topic.name,
      objectives,
      demonstrable: objectives.filter((objective) => objective.verdict === "demonstrable").length,
    };
  });
}

const MARK: Record<ObjectiveVerdict, string> = {
  demonstrable: "**demonstrable**",
  "evidence-only": "evidence only",
  "not-assessable": "not assessable",
};

export function renderCoverage(topics: TopicRow[]): string {
  const available = availableCompetencyIds();
  const objectives = topics.flatMap((topic) => topic.objectives);
  const covered = topics.filter((topic) => topic.demonstrable > 0);
  const lines: string[] = [];

  lines.push("# What BOW can assess");
  lines.push("");
  lines.push("<!-- Generated by scripts/module-coverage.ts. Do not edit by hand; moduleCoverage.test.ts");
  lines.push("     regenerates this file and fails if the committed copy disagrees with the code. -->");
  lines.push("");
  lines.push(
    `**${covered.length} of ${topics.length} NYSED topics** have at least one demonstrable objective. ` +
      `**${objectives.filter((objective) => objective.verdict === "demonstrable").length} of ${objectives.length} objectives** ` +
      `are demonstrable today.`,
  );
  lines.push("");
  lines.push(
    "An objective is *demonstrable* when a competency mapped `full` to it is built into at least " +
      "one world — or, where the objective bundles several skills under one number, when every " +
      "competency its completion rule names is. *Evidence only* means a student's work speaks to " +
      "the objective and does not settle it: a `partial` mapping is real evidence and is never a " +
      "demonstration. *Not assessable* means BOW has no world that asks a student for it, which " +
      "is a statement about this product and not about any student.",
  );
  lines.push("");

  for (const topic of topics) {
    lines.push(`## Topic ${topic.code} — ${topic.name}`);
    lines.push("");
    lines.push(`${topic.demonstrable} of ${topic.objectives.length} objectives demonstrable.`);
    lines.push("");
    lines.push("| Objective | | Rests on |");
    lines.push("| --- | --- | --- |");
    for (const objective of topic.objectives) {
      const rests = objective.requires
        ? `all of ${objective.requires.map((entry) => `\`${entry.competencyId}\`${entry.available ? "" : " *(no world)*"}`).join(", ")}`
        : objective.fullMappings.length === 0
          ? "*no competency covers the whole of it*"
          : objective.fullMappings
              .map((entry) => `\`${entry.competencyId}\`${entry.available ? "" : " *(no world)*"}`)
              .join(", ");
      lines.push(`| ${objective.code} ${objective.shortLabel} | ${MARK[objective.verdict]} | ${rests} |`);
    }
    lines.push("");
  }

  lines.push("## Why the gap is the shape it is");
  lines.push("");
  const unwritten = COMPETENCIES.filter((competency) => competency.evidenceRequirements.length === 0);
  const writtenNoWorld = COMPETENCIES.filter(
    (competency) => competency.evidenceRequirements.length > 0 && !available.has(competency.id),
  );
  lines.push(
    `Of ${COMPETENCIES.length} competencies, **${available.size} are built**. ` +
      `**${unwritten.length} have no evidence requirements written at all** — they are declared, grouped and ` +
      "mapped, and nothing has yet said what would count as a student demonstrating them, so no world " +
      "can produce them and none is reported as assessable. " +
      `**${writtenNoWorld.length}** ${writtenNoWorld.length === 1 ? "has its requirements written and no world that asks for them" : "have their requirements written and no world that asks for them"}.`,
  );
  lines.push("");
  lines.push("| Competency | State |");
  lines.push("| --- | --- |");
  for (const competency of COMPETENCIES) {
    const worlds = worldsAssessing(competency.id);
    const state = available.has(competency.id)
      ? `built · ${worlds.join(", ")}`
      : competency.evidenceRequirements.length === 0
        ? "no evidence requirements written"
        : `${requiredEvidenceRequirementsFor(competency.id).length} requirements written · no world produces them`;
    lines.push(`| \`${competency.id}\` ${competency.displayCode} | ${state} |`);
  }
  lines.push("");
  return lines.join("\n");
}

if (process.argv[1]?.endsWith("module-coverage.ts")) {
  const { writeFileSync } = await import("node:fs");
  writeFileSync("MODULE_COVERAGE.md", renderCoverage(readCoverage()));
  process.stdout.write("MODULE_COVERAGE.md written\n");
}
